name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Esto hará que el pipeline se ejecute cuando hagas push en la rama principal
  pull_request:
    branches:
      - main  # También se ejecutará para los pull requests hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Esto hace que se ejecute en un entorno de Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Esto descarga el código de tu repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Instala Node.js en el entorno

      - name: Run test script
        run: node test.js  # Esto ejecuta el archivo test.js en Node.js
